
obj-y += platform_resource.o disp_board_config.o

obj-$(CONFIG_ARCH_SUN8IW19) += sun8iw19.o
obj-$(CONFIG_ARCH_SUN8IW20) += sun8iw20.o
obj-$(CONFIG_ARCH_SUN20IW1) += sun20iw1.o
obj-$(CONFIG_ARCH_SUN20IW2) += sun20iw2.o

obj-$(CONFIG_V459_PERF1) += v459_perf1.o
obj-$(CONFIG_F133_FPGA) += f133_fpga.o

obj-$(CONFIG_VVX07H005A10_MIPI) += VVX07H005A10_mipi_config.o
obj-$(CONFIG_HE0801A068_MIPI)+= he0801a068_mipi_config.o
obj-$(CONFIG_GC9503CV_MIPI) += gc9503cv_mipi_config.o
obj-$(CONFIG_T070S140B_MIPI) += t070s140b_mipi_config.o
obj-$(CONFIG_BOE_1200X1920_MIPI) += BOE_1200x1920_mipi_config.o
obj-$(CONFIG_SSD1306_SPI) += ssd1306_spi_config.o
obj-$(CONFIG_DEFAULT_LVDS)+= f133_lvds.o
obj-$(CONFIG_LCD_SUPPORT_ILI9341)+= ili9341_lcd_spi.o
obj-$(CONFIG_LCD_SUPPORT_ST7789)+= st7789_lcd_spi.o
