abufsrc@Music=outputs=1:map=1[Music0],

abufsrc@Ring=outputs=1:map=1[Ring0],

abufsrc@Alarm=outputs=1:map=1[Alarm0],

abufsrc@Notify=outputs=1:map=1[Notify0],

abufsrc@TTS=outputs=1:map=1[TTS0],

abufsrc@Sport=outputs=1:map=1[Sport0],

abufsrc@Media=outputs=1:map=1[Media0],

abufsrc@Enforced=outputs=1:map=1[Enforced0],

[Music0][Ring0][Alarm0][Notify0][TTS0][Sport0][Media0][Enforced0]alsasink@pcm0p=inputs=8:devname=pcm0p,

alsasrc@pcm0c=devname=pcm0c:outputs=1:map=1[cap0],

[cap0]abufsink@Capture=inputs=1
